controllers/GridGroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\GridGrouping;
use app\models\KartikForm;
use app\models\search\GridGrouping as GridGroupingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use kartik\mpdf\Pdf;

/**
 * GridGroupController implements the CRUD actions for GridGrouping model.
 */
class GridGroupController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all GridGrouping models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GridGroupingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single GridGrouping model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new GridGrouping model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new GridGrouping();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing GridGrouping model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing GridGrouping model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionFormTag(){ 
    	  $model = new KartikForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['form-tag', 'id' => $model->id]);
        }

        return $this->render('form-tag', [
            'model' => $model,
        ]);
    }

    public function actionKartikExtensions(){ 
        return $this->render('kartik-extensions', [
            'model' => new KartikForm(),
        ]);
    }

    public function actionSubcat() {
    $out = [];
    if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
            $cat_id = $parents[0];
            switch ($cat_id) {
                case 1:
                    $out = [['id'=>1,'name'=>'Option 1 Sub Option'],['id'=>2,'name'=>'Option 1 Sub Option'],['id'=>3,'name'=>'Option 1 Sub Option']];
                    break;
                case 2:
                    $out = [['id'=>1,'name'=>'Option 2 Sub Option'],['id'=>2,'name'=>'Option 2 Sub Option'],['id'=>3,'name'=>'Option 2 Sub Option']];
                    break;
                
                default:
                    $out = [['id'=>1,'name'=>'Sub Option'],['id'=>2,'name'=>'Sub Option']];
                    break;
            }
            echo Json::encode(['output'=>$out, 'selected'=>'']);
            return;
        }
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
}

    public function actionMpdfDemo1() {
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
            'content' => 'hi this is test page',
            // 'content' => $this->renderAjax('privacy'),
            'options' => [
                'title' => 'Privacy Policy - Krajee.com',
                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
            'methods' => [
                'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);
        return $pdf->render();
    }

    public function actionDatesFormat(){
    	  $model = new KartikForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['dates-format', 'id' => $model->id]);
        }

        return $this->render('dates-format', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the GridGrouping model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GridGrouping the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = GridGrouping::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => "Krajee Yii Extensions",
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Group Grids', 'url' => ['/grid-group/index']],
            [
                'label' => 'Extensions',
                'items' => [
                    ['label' => 'Kartik Forms', 'url' => ['/grid-group/form-tag']],
                    ['label' => 'Kartik Date Formats', 'url' => ['/grid-group/dates-format']],
                    ['label' => 'General Extensions', 'url' => ['/grid-group/kartik-extensions']],
            ],
        ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>